-- MySQL Script generated by MySQL Workbench
-- Wed Sep  1 15:25:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database oc-p5
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `oc-p5` DEFAULT CHARACTER SET utf8 ;
USE `oc-p5` ;

-- -----------------------------------------------------
-- Table `oc-p5`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc-p5`.`user` ;

CREATE TABLE IF NOT EXISTS `oc-p5`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `role` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `verified` TINYINT NOT NULL DEFAULT 0,
  `verification_token` VARCHAR(255) NULL DEFAULT NULL,
  `forgot_password_token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oc-p5`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc-p5`.`admin` ;

CREATE TABLE IF NOT EXISTS `oc-p5`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `catch_phrase` VARCHAR(255) NOT NULL,
  `url_cv` VARCHAR(255) NOT NULL,
  `url_picture` VARCHAR(255) NOT NULL,
  `alt_picture` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ADMIN_USER_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `oc-p5`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `FK_ADMIN_USER_1_idx` ON `oc-p5`.`admin` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `oc-p5`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc-p5`.`post` ;

CREATE TABLE IF NOT EXISTS `oc-p5`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `slug` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `url_coverage_image` VARCHAR(255) NOT NULL,
  `alt_coverage_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_POST_ADMIN_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `oc-p5`.`admin` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `FK_POST_ADMIN_1_idx` ON `oc-p5`.`post` (`admin_id` ASC);


-- -----------------------------------------------------
-- Table `oc-p5`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc-p5`.`comment` ;

CREATE TABLE IF NOT EXISTS `oc-p5`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `post_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `content` TEXT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_COMMENT_POST_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `oc-p5`.`post` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COMMENT_USER_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `oc-p5`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `FK_COMMENT_POST_1_idx` ON `oc-p5`.`comment` (`post_id` ASC);

CREATE INDEX `FK_COMMENT_USER_1_idx` ON `oc-p5`.`comment` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `oc-p5`.`social`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oc-p5`.`social` ;

CREATE TABLE IF NOT EXISTS `oc-p5`.`social` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp(),
  `name` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
