home:
  uri: /
  controller: IndexController
  action: showHome
  parameters: [ ]
contact:
  uri: /contact
  controller: IndexController
  action: showContact
  parameters: [ ]
blog:
  uri: /blog
  controller: BlogController
  action: showBlog
  parameters: [ ]
blogPaging:
  uri: /blog/pages/([a-zA-Z0-9-]+)
  controller: BlogController
  action: showBlog
  parameters: ["page"]
singlePost:
  uri: /blog/([a-zA-Z0-9-]+)
  controller: BlogController
  action: showPost
  parameters: ["slug"]
login:
  uri: /login
  controller: AccountController
  action: login
  parameters: [ ]
logout:
  uri: /logout
  controller: AccountController
  action: logout
  parameters: [ ]
register:
  uri: /register
  controller: AccountController
  action: register
  parameters: [ ]
resend:
  uri: /resend
  controller: AccountController
  action: resend
  parameters: [ ]
verify:
  uri: /verify/([a-zA-Z0-9-]+)
  controller: AccountController
  action: verify
  parameters: [verificationToken]
forget:
  uri: /forget
  controller: AccountController
  action: forget
  parameters: []
newPassword:
  uri: /forget/([a-zA-Z0-9-]+)
  controller: AccountController
  action: forget
  parameters: [forgotPasswordToken]
profile:
  uri: /admin
  controller: AdminController
  action: showProfile
  parameters: [ ]
showSocial:
  uri: /admin/social
  controller: AdminController
  action: showSocial
  parameters: [ ]
addSocial:
  uri: /admin/social/add
  controller: AdminController
  action: addSocial
  parameters: [ ]
editSocial:
  uri: /admin/social/([a-zA-Z0-9-]+)/edit
  controller: AdminController
  action: editSocial
  parameters: ["id"]
deleteSocial:
  uri: /admin/social/([a-zA-Z0-9-]+)/delete
  controller: AdminController
  action: deleteSocial
  parameters: ["id"]
showPost:
  uri: /admin/blog
  controller: AdminController
  action: showPost
  parameters: [ ]
addPost:
  uri: /admin/blog/add
  controller: AdminController
  action: addPost
  parameters: [ ]
editPost:
  uri: /admin/blog/([a-zA-Z0-9-]+)/edit
  controller: AdminController
  action: editPost
  parameters: ["slug"]
deletePost:
  uri: /admin/blog/([a-zA-Z0-9-]+)/delete
  controller: AdminController
  action: deletePost
  parameters: ["slug"]
showComment:
  uri: /admin/comment
  controller: CommentController
  action: showComment
  parameters: [ ]
putCommentOnline:
  uri: /admin/comment/([a-zA-Z0-9-]+)/put-online
  controller: CommentController
  action: putOnline
  parameters: ["id"]
putCommentOffline:
  uri: /admin/comment/([a-zA-Z0-9-]+)/put-offline
  controller: CommentController
  action: putOffline
  parameters: ["id"]