home:
  uri: /
  controller: IndexController
  action: showHome
  parameters: [ ]
contact:
  uri: /contact
  controller: IndexController
  action: showContact
  parameters: [ ]
blog:
  uri: /blog
  controller: BlogController
  action: showBlog
  parameters: [ ]
singlePost:
  uri: /blog/([a-zA-Z0-9-]+)
  controller: BlogController
  action: showPost
  parameters: ["slug"]
login:
  uri: /login
  controller: AccountController
  action: login
  parameters: [ ]
register:
  uri: /register
  controller: AccountController
  action: register
  parameters: [ ]
addPost:
  uri: /admin/blog/add/
  controller: AdminController
  action: addPost
  parameters: [ ]
editPost:
  uri: /admin/blog/([a-zA-Z0-9-]+)/edit/
  controller: AdminController
  action: editPost
  parameters: ["slug"]
deletePost:
  uri: /admin/blog/([a-zA-Z0-9-]+)/delete/
  controller: AdminController
  action: deletePost
  parameters: ["slug"]
putCommentOnline:
  uri: /admin/comment/([a-zA-Z0-9-]+)/put-online/
  controller: CommentController
  action: putOnline
  parameters: ["id"]
putCommentOffline:
  uri: /admin/comment/([a-zA-Z0-9-]+)/put-offline/
  controller: CommentController
  action: putOffline
  parameters: ["id"]